# Generated by Django 5.2.8 on 2025-11-10 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flock_type', models.CharField(choices=[('layers', 'Layers'), ('broilers', 'Broilers'), ('others', 'Others')], max_length=25)),
                ('number_of_birds', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('age', models.PositiveIntegerField(help_text='Age in Days')),
                ('supplier', models.CharField(max_length=100)),
                ('housing', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
